import {
  BabyFoodIcon,
  BeverageIcon,
  ConfectioneryIcon,
  DairyIcon,
  DryGroceryIcon,
  FreshFoodIcon,
  FrozenGroceryIcon,
  HealthyFoodIcon,
  MeatIcon,
  NonFoodIcon,
  PastryIcon,
  SeaFoodIcon,
  FurnitureIcon,
  OfficeMachineIcon,
  StationeryIcon,
  PantryIcon,
  DeliIcon,
  BodySupportIcon,
  HomeHygieneIcon,
  FitnessIcon,
  HomeCareIcon,
  HygieneDisposableIcon,
  RespiratoryIcon,
  ShakersIcon,
  VitaminsIcon,
  PersonalHygiene,
  PetSuppliesIcon,
  BeautyCareIcon,
  TonerInkIcon,
  OfficeFurnitureIcon,
  PaperProductsIcon,
  ElectronicsIcon,
  BabyCareIcon,
  UniformsIcon,
} from './product-categories';

export const CATEGORY_ICONS = {
  'baby-food': BabyFoodIcon,
  beverage: BeverageIcon,
  confectionery: ConfectioneryIcon,
  dairy: DairyIcon,
  'dry-grocery': DryGroceryIcon,
  'fresh-food': FreshFoodIcon,
  'frozen-grocery': FrozenGroceryIcon,
  'healthy-food': HealthyFoodIcon,
  meat: MeatIcon,
  'non-food': NonFoodIcon,
  pastry: PastryIcon,
  'sea-food': SeaFoodIcon,
  'boards-and-furniture': FurnitureIcon,
  'office-machine': OfficeMachineIcon,
  stationery: StationeryIcon,
  'pantry-and-janitorial': PantryIcon,
  deli: DeliIcon,
  'body-support': BodySupportIcon,
  'home-hygiene': HomeHygieneIcon,
  fitness: FitnessIcon,
  'home-care-equipment': HomeCareIcon,
  'hygiene-disposable': HygieneDisposableIcon,
  'respiratory-support': RespiratoryIcon,
  'supplementary-shakers': ShakersIcon,
  'nutrition-and-vitamins': VitaminsIcon,
  'personal-hygiene': PersonalHygiene,
  'pet-supplies': PetSuppliesIcon,
  'beauty-care': BeautyCareIcon,
  electronics: ElectronicsIcon,
  'paper-products': PaperProductsIcon,
  'office-furniture': OfficeFurnitureIcon,
  'toner-ink': TonerInkIcon,
  'baby-care': BabyCareIcon,
  uniforms: UniformsIcon,
};

export const CATEGORY_ICON_NAMES = (Object.keys(
  CATEGORY_ICONS
) as unknown) as (keyof typeof CATEGORY_ICONS)[];
