import isEqual from 'lodash.isequal';
import { ControlProps, Styles } from 'react-select';

import theme from '../../theme';

const important = (str: string | number) => `${str} !important`;

const {
  colors: { gray, orange, red },
  space,
  shadows,
  fontSizes,
  fonts,
} = theme;

export function controlStyles(state: ControlProps<any, any>) {
  switch (true) {
    case state.isDisabled:
      return {
        borderColor: important(gray[50]),
        color: gray[400],
        background: gray[50],
      };
    case state.isFocused:
      return {
        borderColor: important(gray[500]),
        boxShadow: shadows['outline'],
      };
    case state.selectProps.isInvalid:
      return {
        borderColor: important(red[500]),
      };
    default:
      return { borderColor: important(gray[300]) };
  }
}

export function singleSelectMiddleware(options: any[]) {
  return {
    getItemValue: (option?: any) => option?.value,
    getValue: (value?: any) => {
      if (value === null) return null;
      return value
        ? options.find(option => isEqual(option.value, value))
        : undefined;
    },
  };
}

export function multiSelectMiddleware(options: any[]) {
  return {
    getItemValue: (values: any[]) => values?.map(option => option.value) ?? [],
    getValue: (values?: any[]) => {
      if (values === null) return null;
      const result = !!values
        ? options.filter(option => values.includes(option.value))
        : undefined;

      return result;
    },
  };
}

export const styles: Styles<any, any> = {
  container: provided => ({
    ...provided,
    fontFamily: fonts['body'],
    fontSize: fontSizes['md'],
    flex: 1,
  }),
  option: (provided, state) => ({
    ...provided,
    color: state.isDisabled ? gray[300] : gray[700],
    paddingInlineStart: space['sm'],
    paddingInlineEnd: space['sm'],
    minHeight: 34,
    display: 'flex',
    alignItems: 'center',
    cursor: 'pointer',
    background: state.isFocused ? gray[100] : 'white',
    '&:active': {
      background: gray[200],
    },
  }),
  control: (provided, state) => ({
    ...provided,
    border: `1px solid`,
    ...controlStyles(state),
    minHeight: 40,
    '&:hover': {
      borderColor: gray[400],
    },
  }),
  valueContainer: provided => ({
    ...provided,
    paddingInlineStart: space['sm'],
    paddingInlineEnd: space['sm'],
  }),
  singleValue: (provided, state) => {
    const opacity = state.isDisabled ? 0.5 : 1;
    const transition = 'opacity 300ms';

    return { ...provided, opacity, transition };
  },
  dropdownIndicator: (provided, state) => ({
    ...provided,
    color: state.isDisabled ? gray[200] : gray[700],
  }),
  menu: provided => ({
    ...provided,
    zIndex: 100,
    marginTop: space['xs'],
    boxShadow: 'none',
    border: '1px solid',
    borderColor: important(gray[200]),
  }),
  placeholder: (provided, state) => ({
    ...provided,
    color: state.isDisabled ? gray[300] : gray[700],
  }),
};

export const noBorderStyles: Styles<any, any> = {
  ...styles,
  container: provided => ({
    ...provided,
    fontFamily: fonts['body'],
    fontSize: fontSizes['md'],
    position: 'unset',
  }),
  control: provided => ({
    ...provided,
    minHeight: 0,
    border: 'unset',
    boxShadow: 'unset',
  }),
  dropdownIndicator: provided => ({
    ...provided,
    padding: 0,
  }),
  valueContainer: provided => ({
    ...provided,
    padding: 0,
    paddingInlineEnd: space['lg'],
  }),
  singleValue: (provided, state) => {
    const opacity = state.isDisabled ? 0.5 : 1;
    const transition = 'opacity 300ms';
    const maxWidth = 'unset';
    const position = 'unset';
    const transform = 'unset';

    return {
      ...provided,
      opacity,
      transition,
      maxWidth,
      position,
      transform,
      margin: 0,
    };
  },
  menu: provided => ({
    ...provided,
    zIndex: 100,
    marginTop: space['xs'],
    boxShadow: 'none',
    border: '1px solid',
    borderColor: important(gray[200]),
    insetInlineStart: 0,
  }),
};

export const autoCompleteStyles = (): Styles<any, any> => {
  return {
    ...styles,
    control: (provided, state) => {
      return {
        ...provided,
        border: 'none',
        background: gray[100],
        ...controlStyles(state),
        minHeight: 40,
        borderRadius: state.selectProps.menuIsOpen ? '4px 4px 0 0' : '4px',
        cursor: 'pointer',
        boxShadow: 'none',
      };
    },
    menu: provided => ({
      ...provided,
      zIndex: 100,
      boxShadow: '0 0 14px 0 rgba(0, 0, 0, 0.12)',
      border: 'none',
      borderRadius: '0 0 3px 3px',
      borderColor: important(gray[200]),
      insetInlineStart: 0,
      margin: 0,
    }),
    indicatorsContainer: (provided, state) => ({
      ...provided,
      transform: state.selectProps.menuIsOpen ? 'rotate(-180deg)' : 'rotate(0)',
    }),
    menuList: () => ({
      padding: '0',
    }),
    option: (provided, state) => ({
      ...provided,
      background: 'none',
      paddingInlineStart: space['sm'],
      paddingInlineEnd: space['sm'],
      paddingTop: space['xs'],
      paddingBottom: space['xs'],
      minHeight: 34,
      display: 'flex',
      alignItems: 'center',
      cursor: 'pointer',
      borderBottom: '1px solid',
      borderColor: gray[100],
      color: state.isDisabled
        ? gray[200]
        : state.isFocused
        ? orange[500]
        : gray[700],
      '&:active': {
        background: 'none',
      },
      '&:last-of-type': {
        border: 'none',
      },
    }),
  };
};

const phoneNumbersEn = [
  { value: '93', label: '(+93) Afghanistan', code: 'AF' },
  { value: '358', label: '(+358) Aland Islands', code: 'AX' },
  { value: '355', label: '(+355) Albania', code: 'AL' },
  { value: '213', label: '(+213) Algeria', code: 'DZ' },
  { value: '1684', label: '(+1684) AmericanSamoa', code: 'AS' },
  { value: '376', label: '(+376) Andorra', code: 'AD' },
  { value: '244', label: '(+244) Angola', code: 'AO' },
  { value: '1264', label: '(+1264) Anguilla', code: 'AI' },
  { value: '672', label: '(+672) Antarctica', code: 'AQ' },
  { value: '1268', label: '(+1268) Antigua and Barbuda', code: 'AG' },
  { value: '54', label: '(+54) Argentina', code: 'AR' },
  { value: '374', label: '(+374) Armenia', code: 'AM' },
  { value: '297', label: '(+297) Aruba', code: 'AW' },
  { value: '61', label: '(+61) Australia', code: 'AU' },
  { value: '43', label: '(+43) Austria', code: 'AT' },
  { value: '994', label: '(+994) Azerbaijan', code: 'AZ' },
  { value: '1242', label: '(+1242) Bahamas', code: 'BS' },
  { value: '973', label: '(+973) Bahrain', code: 'BH' },
  { value: '880', label: '(+880) Bangladesh', code: 'BD' },
  { value: '1246', label: '(+1246) Barbados', code: 'BB' },
  { value: '375', label: '(+375) Belarus', code: 'BY' },
  { value: '32', label: '(+32) Belgium', code: 'BE' },
  { value: '501', label: '(+501) Belize', code: 'BZ' },
  { value: '229', label: '(+229) Benin', code: 'BJ' },
  { value: '1441', label: '(+1441) Bermuda', code: 'BM' },
  { value: '975', label: '(+975) Bhutan', code: 'BT' },
  { value: '591', label: '(+591) Bolivia, Plurinational State of', code: 'BO' },
  { value: '387', label: '(+387) Bosnia and Herzegovina', code: 'BA' },
  { value: '267', label: '(+267) Botswana', code: 'BW' },
  { value: '55', label: '(+55) Brazil', code: 'BR' },
  { value: '246', label: '(+246) British Indian Ocean Territory', code: 'IO' },
  { value: '673', label: '(+673) Brunei Darussalam', code: 'BN' },
  { value: '359', label: '(+359) Bulgaria', code: 'BG' },
  { value: '226', label: '(+226) Burkina Faso', code: 'BF' },
  { value: '257', label: '(+257) Burundi', code: 'BI' },
  { value: '855', label: '(+855) Cambodia', code: 'KH' },
  { value: '237', label: '(+237) Cameroon', code: 'CM' },
  { value: '1', label: '(+1) Canada', code: 'CA' },
  { value: '238', label: '(+238) Cape Verde', code: 'CV' },
  { value: ' 345', label: '(+ 345) Cayman Islands', code: 'KY' },
  { value: '236', label: '(+236) Central African Republic', code: 'CF' },
  { value: '235', label: '(+235) Chad', code: 'TD' },
  { value: '56', label: '(+56) Chile', code: 'CL' },
  { value: '86', label: '(+86) China', code: 'CN' },
  { value: '61', label: '(+61) Christmas Island', code: 'CX' },
  { value: '61', label: '(+61) Cocos (Keeling) Islands', code: 'CC' },
  { value: '57', label: '(+57) Colombia', code: 'CO' },
  { value: '269', label: '(+269) Comoros', code: 'KM' },
  { value: '242', label: '(+242) Congo', code: 'CG' },
  {
    value: '243',
    label: '(+243) Congo, The Democratic Republic of the Congo',
    code: 'CD',
  },
  { value: '682', label: '(+682) Cook Islands', code: 'CK' },
  { value: '506', label: '(+506) Costa Rica', code: 'CR' },
  { value: '225', label: "(+225) Cote d'Ivoire", code: 'CI' },
  { value: '385', label: '(+385) Croatia', code: 'HR' },
  { value: '53', label: '(+53) Cuba', code: 'CU' },
  { value: '357', label: '(+357) Cyprus', code: 'CY' },
  { value: '420', label: '(+420) Czech Republic', code: 'CZ' },
  { value: '45', label: '(+45) Denmark', code: 'DK' },
  { value: '253', label: '(+253) Djibouti', code: 'DJ' },
  { value: '1767', label: '(+1767) Dominica', code: 'DM' },
  { value: '1849', label: '(+1849) Dominican Republic', code: 'DO' },
  { value: '593', label: '(+593) Ecuador', code: 'EC' },
  { value: '20', label: '(+20) Egypt', code: 'EG' },
  { value: '503', label: '(+503) El Salvador', code: 'SV' },
  { value: '240', label: '(+240) Equatorial Guinea', code: 'GQ' },
  { value: '291', label: '(+291) Eritrea', code: 'ER' },
  { value: '372', label: '(+372) Estonia', code: 'EE' },
  { value: '251', label: '(+251) Ethiopia', code: 'ET' },
  { value: '500', label: '(+500) Falkland Islands (Malvinas)', code: 'FK' },
  { value: '298', label: '(+298) Faroe Islands', code: 'FO' },
  { value: '679', label: '(+679) Fiji', code: 'FJ' },
  { value: '358', label: '(+358) Finland', code: 'FI' },
  { value: '33', label: '(+33) France', code: 'FR' },
  { value: '594', label: '(+594) French Guiana', code: 'GF' },
  { value: '689', label: '(+689) French Polynesia', code: 'PF' },
  { value: '241', label: '(+241) Gabon', code: 'GA' },
  { value: '220', label: '(+220) Gambia', code: 'GM' },
  { value: '995', label: '(+995) Georgia', code: 'GE' },
  { value: '49', label: '(+49) Germany', code: 'DE' },
  { value: '233', label: '(+233) Ghana', code: 'GH' },
  { value: '350', label: '(+350) Gibraltar', code: 'GI' },
  { value: '30', label: '(+30) Greece', code: 'GR' },
  { value: '299', label: '(+299) Greenland', code: 'GL' },
  { value: '1473', label: '(+1473) Grenada', code: 'GD' },
  { value: '590', label: '(+590) Guadeloupe', code: 'GP' },
  { value: '1671', label: '(+1671) Guam', code: 'GU' },
  { value: '502', label: '(+502) Guatemala', code: 'GT' },
  { value: '44', label: '(+44) Guernsey', code: 'GG' },
  { value: '224', label: '(+224) Guinea', code: 'GN' },
  { value: '245', label: '(+245) Guinea-Bissau', code: 'GW' },
  { value: '595', label: '(+595) Guyana', code: 'GY' },
  { value: '509', label: '(+509) Haiti', code: 'HT' },
  { value: '379', label: '(+379) Holy See (Vatican City State)', code: 'VA' },
  { value: '504', label: '(+504) Honduras', code: 'HN' },
  { value: '852', label: '(+852) Hong Kong', code: 'HK' },
  { value: '36', label: '(+36) Hungary', code: 'HU' },
  { value: '354', label: '(+354) Iceland', code: 'IS' },
  { value: '91', label: '(+91) India', code: 'IN' },
  { value: '62', label: '(+62) Indonesia', code: 'ID' },
  {
    value: '98',
    label: '(+98) Iran, Islamic Republic of Persian Gulf',
    code: 'IR',
  },
  { value: '964', label: '(+964) Iraq', code: 'IQ' },
  { value: '353', label: '(+353) Ireland', code: 'IE' },
  { value: '44', label: '(+44) Isle of Man', code: 'IM' },
  { value: '972', label: '(+972) Israel', code: 'IL' },
  { value: '39', label: '(+39) Italy', code: 'IT' },
  { value: '1876', label: '(+1876) Jamaica', code: 'JM' },
  { value: '81', label: '(+81) Japan', code: 'JP' },
  { value: '44', label: '(+44) Jersey', code: 'JE' },
  { value: '962', label: '(+962) Jordan', code: 'JO' },
  { value: '77', label: '(+77) Kazakhstan', code: 'KZ' },
  { value: '254', label: '(+254) Kenya', code: 'KE' },
  { value: '686', label: '(+686) Kiribati', code: 'KI' },
  {
    value: '850',
    label: "(+850) Korea, Democratic People's Republic of Korea",
    code: 'KP',
  },
  { value: '82', label: '(+82) Korea, Republic of South Korea', code: 'KR' },
  { value: '965', label: '(+965) Kuwait', code: 'KW' },
  { value: '996', label: '(+996) Kyrgyzstan', code: 'KG' },
  { value: '856', label: '(+856) Laos', code: 'LA' },
  { value: '371', label: '(+371) Latvia', code: 'LV' },
  { value: '961', label: '(+961) Lebanon', code: 'LB' },
  { value: '266', label: '(+266) Lesotho', code: 'LS' },
  { value: '231', label: '(+231) Liberia', code: 'LR' },
  { value: '218', label: '(+218) Libyan Arab Jamahiriya', code: 'LY' },
  { value: '423', label: '(+423) Liechtenstein', code: 'LI' },
  { value: '370', label: '(+370) Lithuania', code: 'LT' },
  { value: '352', label: '(+352) Luxembourg', code: 'LU' },
  { value: '853', label: '(+853) Macao', code: 'MO' },
  { value: '389', label: '(+389) Macedonia', code: 'MK' },
  { value: '261', label: '(+261) Madagascar', code: 'MG' },
  { value: '265', label: '(+265) Malawi', code: 'MW' },
  { value: '60', label: '(+60) Malaysia', code: 'MY' },
  { value: '960', label: '(+960) Maldives', code: 'MV' },
  { value: '223', label: '(+223) Mali', code: 'ML' },
  { value: '356', label: '(+356) Malta', code: 'MT' },
  { value: '692', label: '(+692) Marshall Islands', code: 'MH' },
  { value: '596', label: '(+596) Martinique', code: 'MQ' },
  { value: '222', label: '(+222) Mauritania', code: 'MR' },
  { value: '230', label: '(+230) Mauritius', code: 'MU' },
  { value: '262', label: '(+262) Mayotte', code: 'YT' },
  { value: '52', label: '(+52) Mexico', code: 'MX' },
  {
    value: '691',
    label: '(+691) Micronesia, Federated States of Micronesia',
    code: 'FM',
  },
  { value: '373', label: '(+373) Moldova', code: 'MD' },
  { value: '377', label: '(+377) Monaco', code: 'MC' },
  { value: '976', label: '(+976) Mongolia', code: 'MN' },
  { value: '382', label: '(+382) Montenegro', code: 'ME' },
  { value: '1664', label: '(+1664) Montserrat', code: 'MS' },
  { value: '212', label: '(+212) Morocco', code: 'MA' },
  { value: '258', label: '(+258) Mozambique', code: 'MZ' },
  { value: '95', label: '(+95) Myanmar', code: 'MM' },
  { value: '264', label: '(+264) Namibia', code: 'NA' },
  { value: '674', label: '(+674) Nauru', code: 'NR' },
  { value: '977', label: '(+977) Nepal', code: 'NP' },
  { value: '31', label: '(+31) Netherlands', code: 'NL' },
  { value: '599', label: '(+599) Netherlands Antilles', code: 'AN' },
  { value: '687', label: '(+687) New Caledonia', code: 'NC' },
  { value: '64', label: '(+64) New Zealand', code: 'NZ' },
  { value: '505', label: '(+505) Nicaragua', code: 'NI' },
  { value: '227', label: '(+227) Niger', code: 'NE' },
  { value: '234', label: '(+234) Nigeria', code: 'NG' },
  { value: '683', label: '(+683) Niue', code: 'NU' },
  { value: '672', label: '(+672) Norfolk Island', code: 'NF' },
  { value: '1670', label: '(+1670) Northern Mariana Islands', code: 'MP' },
  { value: '47', label: '(+47) Norway', code: 'NO' },
  { value: '968', label: '(+968) Oman', code: 'OM' },
  { value: '92', label: '(+92) Pakistan', code: 'PK' },
  { value: '680', label: '(+680) Palau', code: 'PW' },
  { value: '970', label: '(+970) Palestinian Territory, Occupied', code: 'PS' },
  { value: '507', label: '(+507) Panama', code: 'PA' },
  { value: '675', label: '(+675) Papua New Guinea', code: 'PG' },
  { value: '595', label: '(+595) Paraguay', code: 'PY' },
  { value: '51', label: '(+51) Peru', code: 'PE' },
  { value: '63', label: '(+63) Philippines', code: 'PH' },
  { value: '872', label: '(+872) Pitcairn', code: 'PN' },
  { value: '48', label: '(+48) Poland', code: 'PL' },
  { value: '351', label: '(+351) Portugal', code: 'PT' },
  { value: '1939', label: '(+1939) Puerto Rico', code: 'PR' },
  { value: '974', label: '(+974) Qatar', code: 'QA' },
  { value: '40', label: '(+40) Romania', code: 'RO' },
  { value: '7', label: '(+7) Russia', code: 'RU' },
  { value: '250', label: '(+250) Rwanda', code: 'RW' },
  { value: '262', label: '(+262) Reunion', code: 'RE' },
  { value: '590', label: '(+590) Saint Barthelemy', code: 'BL' },
  {
    value: '290',
    label: '(+290) Saint Helena, Ascension and Tristan Da Cunha',
    code: 'SH',
  },
  { value: '1869', label: '(+1869) Saint Kitts and Nevis', code: 'KN' },
  { value: '1758', label: '(+1758) Saint Lucia', code: 'LC' },
  { value: '590', label: '(+590) Saint Martin', code: 'MF' },
  { value: '508', label: '(+508) Saint Pierre and Miquelon', code: 'PM' },
  {
    value: '1784',
    label: '(+1784) Saint Vincent and the Grenadines',
    code: 'VC',
  },
  { value: '685', label: '(+685) Samoa', code: 'WS' },
  { value: '378', label: '(+378) San Marino', code: 'SM' },
  { value: '239', label: '(+239) Sao Tome and Principe', code: 'ST' },
  { value: '966', label: '(+966) Saudi Arabia', code: 'SA' },
  { value: '221', label: '(+221) Senegal', code: 'SN' },
  { value: '381', label: '(+381) Serbia', code: 'RS' },
  { value: '248', label: '(+248) Seychelles', code: 'SC' },
  { value: '232', label: '(+232) Sierra Leone', code: 'SL' },
  { value: '65', label: '(+65) Singapore', code: 'SG' },
  { value: '421', label: '(+421) Slovakia', code: 'SK' },
  { value: '386', label: '(+386) Slovenia', code: 'SI' },
  { value: '677', label: '(+677) Solomon Islands', code: 'SB' },
  { value: '252', label: '(+252) Somalia', code: 'SO' },
  { value: '27', label: '(+27) South Africa', code: 'ZA' },
  { value: '211', label: '(+211) South Sudan', code: 'SS' },
  {
    value: '500',
    label: '(+500) South Georgia and the South Sandwich Islands',
    code: 'GS',
  },
  { value: '34', label: '(+34) Spain', code: 'ES' },
  { value: '94', label: '(+94) Sri Lanka', code: 'LK' },
  { value: '249', label: '(+249) Sudan', code: 'SD' },
  { value: '597', label: '(+597) Suriname', code: 'SR' },
  { value: '47', label: '(+47) Svalbard and Jan Mayen', code: 'SJ' },
  { value: '268', label: '(+268) Swaziland', code: 'SZ' },
  { value: '46', label: '(+46) Sweden', code: 'SE' },
  { value: '41', label: '(+41) Switzerland', code: 'CH' },
  { value: '963', label: '(+963) Syrian Arab Republic', code: 'SY' },
  { value: '886', label: '(+886) Taiwan', code: 'TW' },
  { value: '992', label: '(+992) Tajikistan', code: 'TJ' },
  {
    value: '255',
    label: '(+255) Tanzania, United Republic of Tanzania',
    code: 'TZ',
  },
  { value: '66', label: '(+66) Thailand', code: 'TH' },
  { value: '670', label: '(+670) Timor-Leste', code: 'TL' },
  { value: '228', label: '(+228) Togo', code: 'TG' },
  { value: '690', label: '(+690) Tokelau', code: 'TK' },
  { value: '676', label: '(+676) Tonga', code: 'TO' },
  { value: '1868', label: '(+1868) Trinidad and Tobago', code: 'TT' },
  { value: '216', label: '(+216) Tunisia', code: 'TN' },
  { value: '90', label: '(+90) Turkey', code: 'TR' },
  { value: '993', label: '(+993) Turkmenistan', code: 'TM' },
  { value: '1649', label: '(+1649) Turks and Caicos Islands', code: 'TC' },
  { value: '688', label: '(+688) Tuvalu', code: 'TV' },
  { value: '256', label: '(+256) Uganda', code: 'UG' },
  { value: '380', label: '(+380) Ukraine', code: 'UA' },
  { value: '971', label: '(+971) United Arab Emirates', code: 'AE' },
  { value: '44', label: '(+44) United Kingdom', code: 'GB' },
  { value: '001', label: '(+1) United States', code: 'US' },
  { value: '598', label: '(+598) Uruguay', code: 'UY' },
  { value: '998', label: '(+998) Uzbekistan', code: 'UZ' },
  { value: '678', label: '(+678) Vanuatu', code: 'VU' },
  {
    value: '58',
    label: '(+58) Venezuela, Bolivarian Republic of Venezuela',
    code: 'VE',
  },
  { value: '84', label: '(+84) Vietnam', code: 'VN' },
  { value: '1284', label: '(+1284) Virgin Islands, British', code: 'VG' },
  { value: '1340', label: '(+1340) Virgin Islands, U.S.', code: 'VI' },
  { value: '681', label: '(+681) Wallis and Futuna', code: 'WF' },
  { value: '967', label: '(+967) Yemen', code: 'YE' },
  { value: '260', label: '(+260) Zambia', code: 'ZM' },
  { value: '263', label: '(+263) Zimbabwe', code: 'ZW' },
];

const phoneNumbersAr = [
  { value: '93', label: '(93+) أفغانستان', code: 'AF' },
  { value: '358', label: '(358+) جزر آلاند', code: 'AX' },
  { value: '355', label: '(355+) ألبانيا', code: 'AL' },
  { value: '213', label: '(213+) الجزائر', code: 'DZ' },
  { value: '1684', label: '(1684+) ساموا الأمريكية', code: 'AS' },
  { value: '376', label: '(376+) أندورا', code: 'AD' },
  { value: '244', label: '(244+) أنغولا', code: 'AO' },
  { value: '1264', label: '(1264+) أنغيلا', code: 'AI' },
  { value: '672', label: '(672+) القارة القطبية الجنوبية', code: 'AQ' },
  { value: '1268', label: '(1268+) أنتيغوا وباربودا', code: 'AG' },
  { value: '54', label: '(54+) الأرجنتين', code: 'AR' },
  { value: '374', label: '(374+) أرمينيا', code: 'AM' },
  { value: '297', label: '(297+) أروبا', code: 'AW' },
  { value: '61', label: '(61+) أستراليا', code: 'AU' },
  { value: '43', label: '(43+) النمسا', code: 'AT' },
  { value: '994', label: '(994+) أذربيجان', code: 'AZ' },
  { value: '1242', label: '(1242+) البهاما', code: 'BS' },
  { value: '973', label: '(973+) البحرين', code: 'BH' },
  { value: '880', label: '(880+) بنغلاديش', code: 'BD' },
  { value: '1246', label: '(1246+) باربادوس', code: 'BB' },
  { value: '375', label: '(375+) بيلاروسيا', code: 'BY' },
  { value: '32', label: '(32+) بلجيكا', code: 'BE' },
  { value: '501', label: '(501+) بليز', code: 'BZ' },
  { value: '229', label: '(229+) بنين', code: 'BJ' },
  { value: '1441', label: '(1441+) برمودا', code: 'BM' },
  { value: '975', label: '(975+) بوتان', code: 'BT' },
  { value: '591', label: '(591+) بوليفيا', code: 'BO' },
  { value: '387', label: '(387+) البوسنة والهرسك', code: 'BA' },
  { value: '267', label: '(267+) بوتسوانا', code: 'BW' },
  { value: '55', label: '(55+) البرازيل', code: 'BR' },
  { value: '246', label: '(246+) إقليم المحيط البريطاني الهندي', code: 'IO' },
  { value: '673', label: '(673+) بروناي', code: 'BN' },
  { value: '359', label: '(359+) بلغاريا', code: 'BG' },
  { value: '226', label: '(226+) بوركينا فاسو', code: 'BF' },
  { value: '257', label: '(257+) بوروندي', code: 'BI' },
  { value: '855', label: '(855+) كمبوديا', code: 'KH' },
  { value: '237', label: '(237+) الكاميرون', code: 'CM' },
  { value: '1', label: '(1+) كندا', code: 'CA' },
  { value: '238', label: '(238+) الرأس الأخضر', code: 'CV' },
  { value: ' 345', label: '(345+) جزر كايمان', code: 'KY' },
  { value: '236', label: '(236+) جمهورية أفريقيا الوسطى', code: 'CF' },
  { value: '235', label: '(235+) تشاد', code: 'TD' },
  { value: '56', label: '(56+) تشيلي', code: 'CL' },
  { value: '86', label: '(86+) الصين', code: 'CN' },
  { value: '61', label: '(61+) جزيرة الكريسماس', code: 'CX' },
  { value: '61', label: '(61+) جزر كوكوس (كيلينغ)', code: 'CC' },
  { value: '57', label: '(57+) كولومبيا', code: 'CO' },
  { value: '269', label: '(269+) جزر القمر', code: 'KM' },
  { value: '242', label: '(242+) الكونغو', code: 'CG' },
  { value: '243', label: '(243+) جمهورية الكونغو الديمقراطية', code: 'CD' },
  { value: '682', label: '(682+) جزر كوك', code: 'CK' },
  { value: '506', label: '(506+) كوستاريكا', code: 'CR' },
  { value: '225', label: '(225+) ساحل العاج', code: 'CI' },
  { value: '385', label: '(385+) كرواتيا', code: 'HR' },
  { value: '53', label: '(53+) كوبا', code: 'CU' },
  { value: '357', label: '(357+) قبرص', code: 'CY' },
  { value: '420', label: '(420+) التشيك', code: 'CZ' },
  { value: '45', label: '(45+) الدنمارك', code: 'DK' },
  { value: '253', label: '(253+) جيبوتي', code: 'DJ' },
  { value: '1767', label: '(1767+) دومينيكا', code: 'DM' },
  { value: '1849', label: '(1849+) جمهورية الدومينيكان', code: 'DO' },
  { value: '593', label: '(593+) الإكوادور', code: 'EC' },
  { value: '20', label: '(20+) مصر', code: 'EG' },
  { value: '503', label: '(503+) السلفادور', code: 'SV' },
  { value: '240', label: '(240+) غينيا الاستوائية', code: 'GQ' },
  { value: '291', label: '(291+) إريتريا', code: 'ER' },
  { value: '372', label: '(372+) إستونيا', code: 'EE' },
  { value: '251', label: '(251+) إثيوبيا', code: 'ET' },
  { value: '500', label: '(500+) جزر فوكلاند', code: 'FK' },
  { value: '298', label: '(298+) جزر فاروس', code: 'FO' },
  { value: '679', label: '(679+) فيجي', code: 'FJ' },
  { value: '358', label: '(358+) فنلندا', code: 'FI' },
  { value: '33', label: '(33+) فرنسا', code: 'FR' },
  { value: '594', label: '(594+) غينيا الفرنسية', code: 'GF' },
  { value: '689', label: '(689+) بولينيزيا الفرنسية', code: 'PF' },
  { value: '241', label: '(241+) الغابون', code: 'GA' },
  { value: '220', label: '(220+) غامبيا', code: 'GM' },
  { value: '995', label: '(995+) جورجيا', code: 'GE' },
  { value: '49', label: '(49+) ألمانيا', code: 'DE' },
  { value: '233', label: '(233+) غانا', code: 'GH' },
  { value: '350', label: '(350+) جبل طارق', code: 'GI' },
  { value: '30', label: '(30+) اليونان', code: 'GR' },
  { value: '299', label: '(299+) جرينلاند', code: 'GL' },
  { value: '1473', label: '(1473+) جرينادا', code: 'GD' },
  { value: '590', label: '(590+) غوادلوب', code: 'GP' },
  { value: '1671', label: '(1671+) غوام', code: 'GU' },
  { value: '502', label: '(502+) غواتيمالا', code: 'GT' },
  { value: '44', label: '(44+) جيرنسي', code: 'GG' },
  { value: '224', label: '(224+) غينيا', code: 'GN' },
  { value: '245', label: '(245+) غينيا بيساو', code: 'GW' },
  { value: '595', label: '(595+) غويانا', code: 'GY' },
  { value: '509', label: '(509+) هايتي', code: 'HT' },
  { value: '379', label: '(379+) الفاتيكان', code: 'VA' },
  { value: '504', label: '(504+) هندوراس', code: 'HN' },
  { value: '852', label: '(852+) هونغ كونغ', code: 'HK' },
  { value: '36', label: '(36+) المجر', code: 'HU' },
  { value: '354', label: '(354+) آيسلندا', code: 'IS' },
  { value: '91', label: '(91+) الهند', code: 'IN' },
  { value: '62', label: '(62+) إندونيسيا', code: 'ID' },
  { value: '98', label: '(98+) إيران', code: 'IR' },
  { value: '964', label: '(964+) العراق', code: 'IQ' },
  { value: '353', label: '(353+) جمهورية أيرلندا', code: 'IE' },
  { value: '44', label: '(44+) جزيرة مان', code: 'IM' },
  { value: '972', label: '(972+) إسرائيل', code: 'IL' },
  { value: '39', label: '(39+) إيطاليا', code: 'IT' },
  { value: '1876', label: '(1876+) جامايكا', code: 'JM' },
  { value: '81', label: '(81+) اليابان', code: 'JP' },
  { value: '44', label: '(44+) جيرسي', code: 'JE' },
  { value: '962', label: '(962+) الأردن', code: 'JO' },
  { value: '77', label: '(77+) كازاخستان', code: 'KZ' },
  { value: '254', label: '(254+) كينيا', code: 'KE' },
  { value: '686', label: '(686+) كيريباتي', code: 'KI' },
  { value: '850', label: '(850+) كوريا الشمالية', code: 'KP' },
  { value: '82', label: '(82+) كوريا الجنوبية', code: 'KR' },
  { value: '965', label: '(965+) الكويت', code: 'KW' },
  { value: '996', label: '(996+) قرغيزستان', code: 'KG' },
  { value: '856', label: '(856+) لاوس', code: 'LA' },
  { value: '371', label: '(371+) لاتفيا', code: 'LV' },
  { value: '961', label: '(961+) لبنان', code: 'LB' },
  { value: '266', label: '(266+) ليسوتو', code: 'LS' },
  { value: '231', label: '(231+) ليبيريا', code: 'LR' },
  { value: '218', label: '(218+) ليبيا', code: 'LY' },
  { value: '423', label: '(423+) ليختنشتاين', code: 'LI' },
  { value: '370', label: '(370+) ليتوانيا', code: 'LT' },
  { value: '352', label: '(352+) لوكسمبورغ', code: 'LU' },
  { value: '853', label: '(853+) ماكاو', code: 'MO' },
  {
    value: '389',
    label: '(389+) (مقدونيا (جمهورية مقدونيا اليوغوسلافية السابقة',
    code: 'MK',
  },
  { value: '261', label: '(261+) مدغشقر', code: 'MG' },
  { value: '265', label: '(265+) مالاوي', code: 'MW' },
  { value: '60', label: '(60+) ماليزيا', code: 'MY' },
  { value: '960', label: '(960+) جزر المالديف', code: 'MV' },
  { value: '223', label: '(223+) مالي', code: 'ML' },
  { value: '356', label: '(356+) مالطا', code: 'MT' },
  { value: '692', label: '(692+) جزر مارشال', code: 'MH' },
  { value: '596', label: '(596+) مارتينيك', code: 'MQ' },
  { value: '222', label: '(222+) موريتانيا', code: 'MR' },
  { value: '230', label: '(230+) موريشيوس', code: 'MU' },
  { value: '262', label: '(262+) مايوت', code: 'YT' },
  { value: '52', label: '(52+) المكسيك', code: 'MX' },
  { value: '691', label: '(691+) مايكرونيزيا', code: 'FM' },
  { value: '373', label: '(373+) مولدوفا', code: 'MD' },
  { value: '377', label: '(377+) موناكو', code: 'MC' },
  { value: '976', label: '(976+) منغوليا', code: 'MN' },
  { value: '382', label: '(382+) الجبل الأسود', code: 'ME' },
  { value: '1664', label: '(1664+) مونتسرات', code: 'MS' },
  { value: '212', label: '(212+) المغرب', code: 'MA' },
  { value: '258', label: '(258+) موزمبيق', code: 'MZ' },
  { value: '95', label: '(95+) بورما', code: 'MM' },
  { value: '264', label: '(264+) ناميبيا', code: 'NA' },
  { value: '674', label: '(674+) ناورو', code: 'NR' },
  { value: '977', label: '(977+) نيبال', code: 'NP' },
  { value: '31', label: '(31+) هولندا', code: 'NL' },
  { value: '599', label: '(599+) جزر الأنتيل الهولندية', code: 'AN' },
  { value: '687', label: '(687+) كاليدونيا الجديدة', code: 'NC' },
  { value: '64', label: '(64+) نيوزيلندا', code: 'NZ' },
  { value: '505', label: '(505+) نيكاراجوا', code: 'NI' },
  { value: '227', label: '(227+) النيجر', code: 'NE' },
  { value: '234', label: '(234+) نيجيريا', code: 'NG' },
  { value: '683', label: '(683+) نييوي', code: 'NU' },
  { value: '672', label: '(672+) جزيرة نورفولك', code: 'NF' },
  { value: '1670', label: '(1670+) جزر ماريانا الشمالية', code: 'MP' },
  { value: '47', label: '(47+) النرويج', code: 'NO' },
  { value: '968', label: '(968+) سلطنة عمان', code: 'OM' },
  { value: '92', label: '(92+) باكستان', code: 'PK' },
  { value: '680', label: '(680+) بالاو', code: 'PW' },
  { value: '970', label: '(970+) الأراضي الفلسطينية المحتلة', code: 'PS' },
  { value: '507', label: '(507+) بنما', code: 'PA' },
  { value: '675', label: '(675+) بابوا غينيا الجديدة', code: 'PG' },
  { value: '595', label: '(595+) باراغواي', code: 'PY' },
  { value: '51', label: '(51+) بيرو', code: 'PE' },
  { value: '63', label: '(63+) الفلبين', code: 'PH' },
  { value: '872', label: '(872+) جزر بيتكيرن', code: 'PN' },
  { value: '48', label: '(48+) بولندا', code: 'PL' },
  { value: '351', label: '(351+) البرتغال', code: 'PT' },
  { value: '1939', label: '(1939+) بورتوريكو', code: 'PR' },
  { value: '974', label: '(974+) قطر', code: 'QA' },
  { value: '40', label: '(40+) رومانيا', code: 'RO' },
  { value: '7', label: '(7+) روسيا', code: 'RU' },
  { value: '250', label: '(250+) رواندا', code: 'RW' },
  { value: '262', label: '(262+) ريونيون', code: 'RE' },
  { value: '590', label: '(590+) سانت بارتيليمي', code: 'BL' },
  { value: '290', label: '(290+) سانت هيلينا', code: 'SH' },
  { value: '1869', label: '(1869+) سانت كيتس ونيفيس', code: 'KN' },
  { value: '1758', label: '(1758+) سانت لوسيا', code: 'LC' },
  { value: '590', label: '(590+) سانت مارتن (الجزء الفرنسي)', code: 'MF' },
  { value: '508', label: '(508+) سان بيار وميكلون', code: 'PM' },
  { value: '1784', label: '(1784+) سانت فنسينت والجرينادينز', code: 'VC' },
  { value: '685', label: '(685+) ساموا', code: 'WS' },
  { value: '378', label: '(378+) سان مارينو', code: 'SM' },
  { value: '239', label: '(239+) ساو تومي وبرينسيب', code: 'ST' },
  { value: '966', label: '(966+) السعودية', code: 'SA' },
  { value: '221', label: '(221+) السنغال', code: 'SN' },
  { value: '381', label: '(381+) صربيا', code: 'RS' },
  { value: '248', label: '(248+) سيشيل', code: 'SC' },
  { value: '232', label: '(232+) سيراليون', code: 'SL' },
  { value: '65', label: '(65+) سنغافورة', code: 'SG' },
  { value: '421', label: '(421+) سلوفاكيا', code: 'SK' },
  { value: '386', label: '(386+) سلوفينيا', code: 'SI' },
  { value: '677', label: '(677+) جزر سليمان', code: 'SB' },
  { value: '252', label: '(252+) الصومال', code: 'SO' },
  { value: '27', label: '(27+) جنوب أفريقيا', code: 'ZA' },
  { value: '211', label: '(211+) جنوب السودان', code: 'SS' },
  {
    value: '500',
    label: '(500+) جورجيا الجنوبية وجزر ساندويتش الجنوبية',
    code: 'GS',
  },
  { value: '34', label: '(34+) إسبانيا', code: 'ES' },
  { value: '94', label: '(94+) سريلانكا', code: 'LK' },
  { value: '249', label: '(249+) السودان', code: 'SD' },
  { value: '597', label: '(597+) سورينام', code: 'SR' },
  { value: '47', label: '(47+) سفالبارد ويان ماين', code: 'SJ' },
  { value: '268', label: '(268+) سوازيلاند', code: 'SZ' },
  { value: '46', label: '(46+) السويد', code: 'SE' },
  { value: '41', label: '(41+) سويسرا', code: 'CH' },
  { value: '963', label: '(963+) سوريا', code: 'SY' },
  { value: '886', label: '(886+) تايوان ، مقاطعة الصين', code: 'TW' },
  { value: '992', label: '(992+) طاجيكستان', code: 'TJ' },
  { value: '255', label: '(255+)تنزانيا', code: 'TZ' },
  { value: '66', label: '(66+) تايلاند', code: 'TH' },
  { value: '670', label: '(670+) تيمور الشرقية', code: 'TL' },
  { value: '228', label: '(228+) توغو', code: 'TG' },
  { value: '690', label: '(690+) توكلو', code: 'TK' },
  { value: '676', label: '(676+) تونجا', code: 'TO' },
  { value: '1868', label: '(1868+) ترينيداد وتوباغو', code: 'TT' },
  { value: '216', label: '(216+) تونس', code: 'TN' },
  { value: '90', label: '(90+) تركيا', code: 'TR' },
  { value: '993', label: '(993+) تركمانستان', code: 'TM' },
  { value: '1649', label: '(1649+) جزر تركس وكايكوس', code: 'TC' },
  { value: '688', label: '(688+) توفالو', code: 'TV' },
  { value: '256', label: '(256+) أوغندا', code: 'UG' },
  { value: '380', label: '(380+) أوكرانيا', code: 'UA' },
  { value: '971', label: '(971+) الإمارات العربية المتحدة', code: 'AE' },
  { value: '44', label: '(44+) المملكة المتحدة', code: 'GB' },
  { value: '001', label: '(1+) الولايات المتحدة', code: 'US' },
  { value: '598', label: '(598+) أوروغواي', code: 'UY' },
  { value: '998', label: '(998+) أوزبكستان', code: 'UZ' },
  { value: '678', label: '(678+) فانواتو', code: 'VU' },
  { value: '58', label: '(58+) فنزويلا', code: 'VE' },
  { value: '84', label: '(84+) فيتنام', code: 'VN' },
  { value: '1284', label: '(1284+) الجزر العذراء البريطانية', code: 'VG' },
  { value: '1340', label: '(1340+) جزر العذراء الأمريكية', code: 'VI' },
  { value: '681', label: '(681+) واليس وفوتونا', code: 'WF' },
  { value: '967', label: '(967+) اليمن', code: 'YE' },
  { value: '260', label: '(260+) زامبيا', code: 'ZM' },
  { value: '263', label: '(263+) زيمبابوي', code: 'ZW' },
];

export const phoneNumbers = (lang: string) =>
  lang === 'ar' ? phoneNumbersAr : phoneNumbersEn;
